# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dstat-interface
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  entry_points:
    - dstat-interface = dstat_interface.main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - matplotlib
    - pandas
    - psutil
    - pycairo-gtk2
    - pyserial
    - pyyaml
    - pyzmq
    - seaborn
    - si-prefix
    - zeo
    - zmq-plugin
    - zodb

  run:
    - matplotlib
    - pandas
    - psutil
    - pycairo-gtk2
    - pyserial
    - pyyaml
    - pyzmq
    - seaborn
    - si-prefix
    - zeo
    - zmq-plugin
    - zodb
